export const legacyRoutes = {
  '/第一章/quickstart/': '/start/',
  '/第一章/pythonenv/': '/guide/environment/',
  '/第一章/command-line-tools/': '/guide/environment/',
  '/第一章/github使用教程/': '/reference/git/',
  '/第二章/API_intro/': '/guide/api/',
  '/第二章/API_python/': '/guide/api/',
  '/第二章/Boost_API/': '/guide/text-to-data/',
  '/第三章/dataPreparation/': '/guide/text-to-data/',
  '/第三章/Evaluation/': '/guide/evaluation/',
  '/第四章/RAG/': '/roadmap/',
  '/第五章/MCP_intro/': '/roadmap/',
  '/第五章/MCP_example/': '/roadmap/',
  '/第六章/autogen/': '/roadmap/',
  '/第六章/coze/': '/roadmap/',
  '/第七章/LLM_example/': '/roadmap/',
  '/附录/README/': '/reference/resources/',
  '/References/': '/reference/resources/',
};
